### ISSUE TITLE
Travis CI Link Updates

### ISSUE THREAD

**Issue by tjconstant** [dickie-roper/inRainbows#3]
Travis build status badge points to fork, not origin repo. Should be as simple as logging into travis.org, enabling repo and then editing README url

**Comment by cj-holmes** [comment]
Yep ok. I'll give that a go

**Comment by cj-holmes** [comment]
Right, had  a go. Took almost 20 minutes for Travis to build and then failed on the author bit, turns out I must've ballsed that up! Will have take a look on the weekend

Malformed Authors@R field:
  <text>:4:0: unexpected end of input
2:   person("Chris", "Holmes", email = "c.holmes4@gmail.com", role = c("aut", "cre")),
3:   person("Tom", "Constant", email = "t.j.constant@gmail.com", role = c("aut", "ctb"))
  ^

**Comment by tjconstant** [comment]
Looks ok! it’s just missing a bracket as authors@R should be a vector of persons. Just an unclosed c(

**Comment by cj-holmes** [comment]
Ah ffs! I checked that a few times, didn't see the open bracket on the line above. That'll teach me to edit code on the website

**Comment by cj-holmes** [comment]
Done
